version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movieflix_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: movieflix_pass
    ports:
      - "3334:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
